title: Andrey Satarin
description: null
author: 
  name: Andrey Satarin
  twitter: asatarin
google_analytics: G-6RQFPSJXCJ
lang: en-US
theme: jekyll-theme-cayman

twitter:
  username: asatarin
  card: summary_large_image

social:
  name: Andrey Satarin
  links:
    - https://twitter.com/asatarin
    - https://www.linkedin.com/in/asatarin
    - https://github.com/asatarin
    - https://discuss.systems/@asatarin
    - https://asatarin.github.io/

feed:
  path: /feed.xml
  posts_limit: 20

defaults:
  - 
    scope:
      path: ""
    values:
      image: /assets/thumbnails/default-thumbnail.png
  - scope:
      path: "/**/*.transcript.md"
    values:
      published: false
      sitemap: false

permalink: /:year/:title/

url: "https://asatarin.github.io" # the base hostname & protocol for the sitemap

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  
kramdown:
  strict_mode: true
