title: Andrey Satarin
description: null
author: 
  twitter: asatarin
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

site:
  author: Andrey Satarin

twitter:
  username: asatarin
  card: summary

social:
  name: Andrey Satarin
  links:
    - https://twitter.com/asatarin
    - https://www.linkedin.com/in/asatarin
    - https://github.com/asatarin
    
permalink: /:categories/:year/:title/

plugins:
  - jekyll-feed
