title: Andrey Satarin
description: Personal Website
author: 
  name: Andrey Satarin
  twitter: asatarin
google_analytics: G-6RQFPSJXCJ
lang: en-US

twitter:
  username: asatarin
  card: summary_large_image

social:
  name: Andrey Satarin
  links:
    - https://twitter.com/asatarin
    - https://www.linkedin.com/in/asatarin
    - https://github.com/asatarin
    - https://discuss.systems/@asatarin
    - https://speakerdeck.com/asatarin
    - https://bsky.app/profile/asatarin.bsky.social

defaults:
  - 
    scope:
      path: ""
    values:
      image: /assets/thumbnails/default-thumbnail.png
  - scope:
      path: "/**/*.transcript.md"
    values:
      published: false
      sitemap: false

permalink: /:year/:title/

url: "https://asatarin.github.io" # the base hostname & protocol for the sitemap

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

markdown: kramdown
kramdown:
  strict_mode: true
