title: Andrey Satarin
description: null
author: 
  name: Andrey Satarin
  twitter: asatarin
google_analytics: G-6RQFPSJXCJ
show_downloads: false
theme: jekyll-theme-cayman

twitter:
  username: asatarin
  card: summary_large_image

social:
  name: Andrey Satarin
  links:
    - https://twitter.com/asatarin
    - https://www.linkedin.com/in/asatarin
    - https://github.com/asatarin

feed:
  path: /test-feed.xml
  posts_limit: 20

defaults:
  - 
    scope:
      path: ""
    values:
      image: /assets/thumbnails/default-thumbnail.png

permalink: /:year/:title/

plugins:
  - jekyll-feed
  - jekyll-redirect-from
