title: Andrey Satarin
description: null
author: 
  name: Andrey Satarin
  twitter: asatarin
google_analytics: UA-127649866-1
show_downloads: false
theme: jekyll-theme-cayman

twitter:
  username: asatarin
  card: summary

social:
  name: Andrey Satarin
  links:
    - https://twitter.com/asatarin
    - https://www.linkedin.com/in/asatarin
    - https://github.com/asatarin

defaults:
  - 
    scope:
      path: ""
    values:
      image: https://i.ytimg.com/vi/BP00xihSQo8/maxresdefault.jpg

permalink: /:categories/:year/:title/

plugins:
  - jekyll-feed
