name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --allow 999 --allow-dupe --allow-ssl --allow-redirect $(find . -name "/github/workspace/*.md")
