name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  linkChecker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: lycheeverse/lychee-action@v2
        with:
          fail: true
          jobSummary: true
          args: >-
            --base .
            --verbose 
            --max-concurrency 5 
            --max-retries 5
            --no-progress
            './**/*.md'
            './**/*.html'
